config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  mount Blazer::Engine, at: "blazer"
  root to: 'home#index'
  post "send_otp" => "users#send_otp"
  get "send_otp" => "users#send_otp"
  post "verify_otp" => "users#verify_otp"
  get "verify_otp" => "users#verify_otp"
  post "resend_otp" => "users#resend_otp"
  get "sign-up" => "users#sign_up"
  post "sign-up" => "users#sign_up_data"
  get "update-profile" => "users#update_profile"
  post "update-profile" => "users#update_profile_data"

  get "issues/list"
  get "issues/want_to_help"
  get "issues/create"
  post "issues/create"
  get "issues/categories"
  get "issues/sub_categories"
  post "issues/resolve"
  post "issues/call_pressed"
  post "issues/issue_help"
  get "issues/search_issues"
  get "users/change_locale"
  post "issues/getIssues"
  get "dashboard" => "dashboard#dashboard"
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="/" target="_parent"><%= image_tag("logo.png", size: '75', class: "img-fluid img-thumbnail") %></a>
    <!--    <b> <%#= t(:title) %></b>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">


      </ul>

      <div class="form-inline my-2 my-lg-0">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t 'language' %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "English", users_change_locale_path({locale: 'en'}), class: "dropdown-item", target: "_parent" %>
              <%= link_to "हिंदी", users_change_locale_path({locale: 'hn'}), class: "dropdown-item", target: "_parent" %>

            </div>
          </li>
        </ul>
        <!--        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
        <% if current_user %>
          <a href=  "update-profile" ><button type="button" class="btn btn-outline-success my-2 mr-3 ml-3"><%= t('Update Profile') %></button></a>
          <label class="btn btn-outline-success my-2 my-sm-0"><%= t('username_html', name: current_user.name) %></label>
        <% end %>
      </div>

    </div>
    <toaster-container toaster-options="{showMethod: 'show', showEasing: 'linear', showDuration: 100, 'close-button':false, 'time-out':{'toast-success': 1500, 'toast-warning': 1500, 'toast-error': 2000 } }">

    </toaster-container>
  </nav>
</header>

app/views/layouts/_side_nav.html.erb
<md-sidenav
  class="md-sidenav-left"
  md-component-id="left"
  md-whiteframe="4">
  <header class="nav-header">
    <a ng-href="/" class="docs-logo" href="/">

      <h1 class="docs-logotype md-heading ng-isolate-scope">AngularJS Material</h1>
    </a>
  </header>
</md-sidenav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Stay united in corona</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app="FightWithCoronaApp">
    <main>
      <%= render 'layouts/header' %>
        <div class="d-flex justify-content-center" style="margin-top: 4.5rem !important;">
          <div class="flex-column flex-lg-40 flex-sm-column">
            <%= yield %>
          </div>

        </div>
    </main>

  </body>
</html>